import type { ColumnConfig } from "@/features/shared/ui/table";
import type { UserOption } from "@/store/useUserStore.";

export const statusLabels: Record<string, string> = {
  contacted: "تماس گرفته شده",
  converted: "تبدیل شده",
  lost: "از دست رفته",
  new: "جدید",
  qualified: "واجد شرایط",
  won: "موفق",
};

export const sourceLabels: Record<string, string> = {
  email: "ایمیل",
  etc: "سایر",
  exhibition: "نمایشگاه",
  instagram: "اینستاگرام",
  telegram: "تلگرام",
  telephone: "تلفن",
};

export const priorityLabels: Record<string, string> = {
  high: "بالا",
  low: "کم",
  medium: "متوسط",
  urgent: "فوری",
};

export const getLeadsColumnConfig = (users: UserOption[] = []): ColumnConfig[] => [
  {
    accessorKey: "firstName",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "نام",
    size: 150,
    sortableFieldName: "firstName",
  },
  {
    accessorKey: "lastName",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "نام خانوادگی",
    size: 150,
    sortableFieldName: "lastName",
  },
  {
    accessorKey: "phone",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "تلفن",
    size: 140,
    sortableFieldName: "phone",
  },
  {
    accessorKey: "email",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "ایمیل",
    size: 200,
    sortableFieldName: "email",
  },
  {
    accessorKey: "status",
    enableFiltering: true,
    enableSorting: true,
    filterType: "select-single",
    header: "وضعیت",
    selectOptions: [
      { label: "جدید", value: "new" },
      { label: "تماس گرفته شده", value: "contacted" },
      { label: "واجد شرایط", value: "qualified" },
      { label: "تبدیل شده", value: "converted" },
      { label: "از دست رفته", value: "lost" },
      { label: "موفق", value: "won" },
    ],
    size: 130,
    sortableFieldName: "status",
  },
  {
    accessorKey: "createdAt",
    enableFiltering: true,
    enableSorting: true,
    filterType: "date-range",
    header: "تاریخ ایجاد",
    size: 140,
    sortableFieldName: "createdAt",
  },
  {
    accessorKey: "assignedToUserId",
    enableFiltering: true,
    enableSorting: true,
    filterType: "select-single",
    header: "ارجاع به",
    selectOptions: users.map((user) => ({
      label: user.label,
      value: String(user.value),
    })),
    size: 140,
    sortableFieldName: "assignedToUserId",
  },
  {
    accessorKey: "company",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "نام مجموعه",
    size: 140,
    sortableFieldName: "company",
  },
  {
    accessorKey: "priority",
    enableFiltering: false,
    enableSorting: false,
    filterType: "select-single",
    header: "اولویت",
    selectOptions: [
      { label: "کم", value: "low" },
      { label: "متوسط", value: "medium" },
      { label: "بالا", value: "high" },
      { label: "فوری", value: "urgent" },
    ],
    size: 120,
    sortableFieldName: "priority",
  },
  {
    accessorKey: "source",
    enableFiltering: true,
    enableSorting: true,
    filterType: "select-single",
    header: "منبع سرنخ",
    selectOptions: [
      { label: "تلفن", value: "telephone" },
      { label: "تلگرام", value: "telegram" },
      { label: "ایمیل", value: "email" },
      { label: "اینستاگرام", value: "instagram" },
      { label: "نمایشگاه", value: "exhibition" },
      { label: "سایر", value: "etc" },
    ],
    size: 110,
    sortableFieldName: "source",
  },
];
