import type { ColumnConfig } from "@/features/shared/ui/table";
import type { UserOption } from "@/store/useUserStore.";

export const statusLabels: Record<string, string> = {
	contacted: "تماس گرفته شده",
	converted: "تبدیل شده",
	lost: "از دست رفته",
	new: "جدید",
	qualified: "واجد شرایط",
	won: "موفق",
};

export const sourceLabels: Record<string, string> = {
	email: "ایمیل",
	etc: "سایر",
	exhibition: "نمایشگاه",
	instagram: "اینستاگرام",
	telegram: "تلگرام",
	telephone: "تلفن",
};

export const priorityLabels: Record<string, string> = {
	high: "بالا",
	low: "کم",
	medium: "متوسط",
	urgent: "فوری",
};

export const getLeadsColumnConfig = (users: UserOption[] = []): ColumnConfig[] => [
	{
		accessorKey: "firstName",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "نام",
		size: 150,
		sortableFieldName: "firstName",
	},
	{
		accessorKey: "lastName",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "نام خانوادگی",
		size: 150,
		sortableFieldName: "lastName",
	},
	{
		accessorKey: "phone",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "تلفن",
		size: 140,
		sortableFieldName: "phone",
	},
	{
		accessorKey: "email",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "ایمیل",
		size: 200,
		sortableFieldName: "email",
	},
	{
		accessorKey: "status",
		badge: {
			contacted: {
				bgColor: "#8b5cf6", 
				label: "تماس گرفته شده",
				textColor: "#ffffff",
				value: "contacted",
			},
			converted: {
				bgColor: "#10b981", 
				label: "تبدیل شده",
				textColor: "#ffffff",
				value: "converted",
			},
			lost: {
				bgColor: "#ef4444", 
				label: "از دست رفته",
				textColor: "#ffffff",
				value: "lost",
			},
			new: {
				bgColor: "#3b82f6", 
				label: "جدید",
				textColor: "#ffffff",
				value: "new",
			},
			qualified: {
				bgColor: "#0891b2", 
				label: "واجد شرایط",
				textColor: "#ffffff",
				value: "qualified",
			},
			won: {
				bgColor: "#16a34a", 
				label: "موفق",
				textColor: "#ffffff",
				value: "won",
			},
		},
		enableFiltering: true,
		enableSorting: true,
		filterType: "select-single",
		header: "وضعیت",
		selectOptions: [
			{ label: "جدید", value: "new" },
			{ label: "تماس گرفته شده", value: "contacted" },
			{ label: "واجد شرایط", value: "qualified" },
			{ label: "تبدیل شده", value: "converted" },
			{ label: "از دست رفته", value: "lost" },
			{ label: "موفق", value: "won" },
		],
		size: 130,
		sortableFieldName: "status",
	},
	{
		accessorKey: "createdAt",
		enableFiltering: true,
		enableSorting: true,
		filterType: "date-range",
		header: "تاریخ ایجاد",
		size: 140,
		sortableFieldName: "createdAt",
	},
	{
		accessorKey: "assignedToUserId",
		enableFiltering: true,
		enableSorting: true,
		filterType: "select-single",
		header: "ارجاع به",
		selectOptions: users.map((user) => ({
			label: user.label,
			value: String(user.value),
		})),
		size: 140,
		sortableFieldName: "assignedToUserId",
	},
	{
		accessorKey: "company",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "نام مجموعه",
		size: 140,
		sortableFieldName: "company",
	},
	{
		accessorKey: "priority",
		badge: {
			high: {
				bgColor: "#dc2626", 
				label: "بالا",
				textColor: "#ffffff",
				value: "high",
			},
			low: {
				bgColor: "#64748b", 
				label: "کم",
				textColor: "#ffffff",
				value: "low",
			},
			medium: {
				bgColor: "#f59e0b", 
				label: "متوسط",
				textColor: "#ffffff",
				value: "medium",
			},
			urgent: {
				bgColor: "#991b1b", 
				label: "فوری",
				textColor: "#ffffff",
				value: "urgent",
			},
		},
		enableFiltering: false,
		enableSorting: false,
		filterType: "select-single",
		header: "اولویت",
		selectOptions: [
			{ label: "کم", value: "low" },
			{ label: "متوسط", value: "medium" },
			{ label: "بالا", value: "high" },
			{ label: "فوری", value: "urgent" },
		],
		size: 120,
		sortableFieldName: "priority",
	},
	{
		accessorKey: "source",
		badge: {
			email: {
				bgColor: "#2563eb", 
				label: "ایمیل",
				textColor: "#ffffff",
				value: "email",
			},
			etc: {
				bgColor: "#6b7280", 
				label: "سایر",
				textColor: "#ffffff",
				value: "etc",
			},
			exhibition: {
				bgColor: "#7c3aed", 
				label: "نمایشگاه",
				textColor: "#ffffff",
				value: "exhibition",
			},
			instagram: {
				bgColor: "#db2777", 
				label: "اینستاگرام",
				textColor: "#ffffff",
				value: "instagram",
			},
			telegram: {
				bgColor: "#0891b2", 
				label: "تلگرام",
				textColor: "#ffffff",
				value: "telegram",
			},
			telephone: {
				bgColor: "#16a34a", 
				label: "تلفن",
				textColor: "#ffffff",
				value: "telephone",
			},
		},
		enableFiltering: true,
		enableSorting: true,
		filterType: "select-single",
		header: "منبع سرنخ",
		selectOptions: [
			{ label: "تلفن", value: "telephone" },
			{ label: "تلگرام", value: "telegram" },
			{ label: "ایمیل", value: "email" },
			{ label: "اینستاگرام", value: "instagram" },
			{ label: "نمایشگاه", value: "exhibition" },
			{ label: "سایر", value: "etc" },
		],
		size: 110,
		sortableFieldName: "source",
	},
];
