import type { ColumnConfig } from "@/features/shared/ui/table";

type RoleOption = {
	label: string;
	value: string;
};

export const getLeadsColumnConfig = (roleOptions: RoleOption[]): ColumnConfig[] => [
	{
		accessorKey: "firstName",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "نام",
		size: 200,
		sortableFieldName: "fullName",
	},
	{
		accessorKey: "lastName",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "نام خانوادگی",
		size: 200,
		sortableFieldName: "fullName",
	},
	{
		accessorKey: "website",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "وبسایت",
		size: 200,
	},
	{
		accessorKey: "phone",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "تلفن",
		size: 200,
	},
	{
		accessorKey: "source",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "منبع",
		size: 200,
	},
	{
		accessorKey: "email",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "ایمیل",
		size: 250,
	},
	{
		accessorKey: "status",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "وضعیت",
		size: 150,
	},
	{
		accessorKey: "createdAt",
		enableFiltering: false,
		enableSorting: false,
		filterType: "date-range",
		header: "تاریخ ایجاد",
		selectOptions: roleOptions,
		size: 150,
	},
	{
		accessorKey: "assignTo",
		enableFiltering: true,
		enableSorting: false,
		filterType: "select-single",
		header: "وبسایت",
		size: 200,
	},
	{
		accessorKey: "createdAt",
		enableFiltering: false,
		enableSorting: false,
		filterType: "text",
		header: "نام مجموعه",
		selectOptions: roleOptions,
		size: 150,
	},
	{
		accessorKey: "اولویت",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "تاریخ ایجاد",
		selectOptions: roleOptions,
		size: 150,
	},
	{
		accessorKey: "LeadSource",
		enableFiltering: true,
		enableSorting: true,
		filterType: "select-single",
		header: "منبع سرنخ",
		selectOptions: roleOptions,
		size: 200,
	},
];
