import type { ColumnConfig } from "@/features/shared/ui/table";

export const getAccountsColumnConfig = (): ColumnConfig[] => [
	{
		accessorKey: "nationalId",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "شناسه ملی",
		size: 140,
		sortableFieldName: "nationalId",
	},
	{
		accessorKey: "name",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "نام سازمان",
		size: 180,
		sortableFieldName: "name",
	},
	{
		accessorKey: "website",
		enableFiltering: true,
		enableSorting: false,
		filterType: "text",
		header: "وب سایت",
		size: 160,
	},
	{
		accessorKey: "phone",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "تلفن",
		size: 140,
		sortableFieldName: "phone",
	},
	{
		accessorKey: "level",
		enableFiltering: true,
		enableSorting: false,
		filterType: "select-single",
		header: "سطح",
		selectOptions: [
			{ label: "طلایی", value: "gold" },
			{ label: "نقره‌ای", value: "silver" },
			{ label: "برنزی", value: "bronze" },
		],
		size: 120,
	},
	{
		accessorKey: "email",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "ایمیل",
		size: 200,
		sortableFieldName: "email",
	},
	{
		accessorKey: "status",
		enableFiltering: true,
		enableSorting: false,
		filterType: "select-single",
		header: "وضعیت",
		selectOptions: [
			{ label: "فعال", value: "active" },
			{ label: "غیرفعال", value: "passive" },
			{ label: "تعلیق", value: "suspension" },
		],
		size: 120,
	},
	{
		accessorKey: "createdAt",
		enableFiltering: true,
		enableSorting: true,
		filterType: "date-range",
		header: "تاریخ ایجاد",
		size: 160,
		sortableFieldName: "createdAt",
	},
	{
		accessorKey: "assignTo",
		enableFiltering: true,
		enableSorting: false,
		filterType: "select-single",
		header: "ارجاع به",
		selectOptions: [
			{ label: "پیش فرض 1", value: "default1" },
			{ label: "پیش فرض 2", value: "default2" },
		],
		size: 140,
	},
];
