import type { ColumnConfig } from "@/features/shared/ui/table";
import { UserOption } from "@/store/useUserStore.";

export const getAccountsColumnConfig = (users: UserOption[] = []): ColumnConfig[] => [
  {
    accessorKey: "nationalId",
    enableFiltering: true,
    enableSorting: false,
    filterType: "text",
    header: "شناسه ملی",
    size: 140,
    sortableFieldName: "nationalId",
  },
  {
    accessorKey: "name",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "نام سازمان",
    size: 160,
    sortableFieldName: "name",
  },
  {
    accessorKey: "website",
    enableFiltering: false,
    enableSorting: false,
    filterType: "text",
    header: "وب سایت",
    size: 140,
  },
  {
    accessorKey: "phone",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "تلفن",
    size: 120,
    sortableFieldName: "phone",
  },
  {
    accessorKey: "level",
    enableFiltering: true,
    enableSorting: false,
    filterType: "select-single",
    header: "سطح",
    selectOptions: [
      { label: "طلایی", value: "gold" },
      { label: "نقره‌ای", value: "silver" },
      { label: "برنزی", value: "bronze" },
    ],
    size: 70,
  },
  {
    accessorKey: "email",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "ایمیل",
    size: 160,
    sortableFieldName: "email",
  },
  {
    accessorKey: "status",
    enableFiltering: true,
    enableSorting: false,
    filterType: "select-single",
    header: "وضعیت",
    selectOptions: [
      { label: "فعال", value: "active" },
      { label: "غیرفعال", value: "passive" },
      { label: "تعلیق", value: "suspension" },
    ],
    size: 70,
  },
  {
    accessorKey: "createdAt",
    enableFiltering: false,
    enableSorting: true,
    filterType: "text",
    header: "تاریخ ایجاد",
    size: 160,
    sortableFieldName: "createdAt",
  },
  {
    accessorKey: "assignedToUserId",
    enableFiltering: true,
    enableSorting: false,
    filterType: "select-single",
    header: "ارجاع به",
    selectOptions: users.map((user) => ({
      label: user.label,
      value: String(user.value),
    })),
    size: 140,
  },
];
