import type { ColumnConfig } from "@/features/shared/ui/table";

export const getAccountsColumnConfig = (): ColumnConfig[] => [
  {
    accessorKey: "nationalId",
    header: "شناسه ملی",
    size: 140,
    enableSorting: true,
    enableFiltering: true,
    filterType: "text",
    sortableFieldName: "nationalId",
  },
  {
    accessorKey: "name",
    header: "نام سازمان",
    size: 180,
    enableSorting: true,
    enableFiltering: true,
    filterType: "text",
    sortableFieldName: "name",
  },
  {
    accessorKey: "website",
    header: "وب سایت",
    size: 160,
    enableSorting: false,
    enableFiltering: true,
    filterType: "text",
  },
  {
    accessorKey: "phone",
    header: "تلفن",
    size: 140,
    enableSorting: true,
    enableFiltering: true,
    filterType: "text",
    sortableFieldName: "phone",
  },
  {
    accessorKey: "level",
    header: "سطح",
    size: 120,
    enableSorting: false,
    enableFiltering: true,
    filterType: "select-single",
    selectOptions: [
      { label: "طلایی", value: "gold" },
      { label: "نقره‌ای", value: "silver" },
      { label: "برنزی", value: "bronze" },
    ],
  },
  {
    accessorKey: "email",
    header: "ایمیل",
    size: 200,
    enableSorting: true,
    enableFiltering: true,
    filterType: "text",
    sortableFieldName: "email",
  },
  {
    accessorKey: "status",
    header: "وضعیت",
    size: 120,
    enableSorting: false,
    enableFiltering: true,
    filterType: "select-single",
    selectOptions: [
      { label: "فعال", value: "active" },
      { label: "غیرفعال", value: "passive" },
      { label: "تعلیق", value: "suspension" },
    ],
  },
  {
    accessorKey: "createdAt",
    header: "تاریخ ایجاد",
    size: 160,
    enableSorting: true,
    enableFiltering: true,
    filterType: "date-range",
    sortableFieldName: "createdAt",
  },
  {
    accessorKey: "assignTo",
    header: "ارجاع به",
    size: 140,
    enableSorting: false,
    enableFiltering: true,
    filterType: "select-single",
    selectOptions: [
      { label: "پیش فرض 1", value: "default1" },
      { label: "پیش فرض 2", value: "default2" },
    ],
  },
];
