import type { Metadata } from "next";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

const IranSansXPro = localFont({
	display: "swap",
	src: [
		{
			path: "./fonts/IranSansXPro/Woff2/IRANSansXFaNum-Thin.woff2",
			style: "normal",
			weight: "300",
		},
		{
			path: "./fonts/IranSansXPro/Woff2/IRANSansXFaNum-Regular.woff2",
			style: "normal",
			weight: "400",
		},
		{
			path: "./fonts/IranSansXPro/Woff2/IRANSansXFaNum-Medium.woff2",
			style: "normal",
			weight: "500",
		},
		{
			path: "./fonts/IranSansXPro/Woff2/IRANSansXFaNum-DemiBold.woff2",
			style: "normal",
			weight: "600",
		},
		{
			path: "./fonts/IranSansXPro/Woff2/IRANSansXFaNum-Bold.woff2",
			style: "normal",
			weight: "700",
		},
		{
			path: "./fonts/IranSansXPro/Woff2/IRANSansXFaNum-Black.woff2",
			style: "normal",
			weight: "900",
		},
	],
	variable: "--font-IranSansXPro",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html dir="rtl" lang="fa" suppressHydrationWarning={true}>
			<body className={cn(IranSansXPro.className, "scrollbar-y-style")}>
				<NextTopLoader color="var(--color-primary)" showSpinner={false} />
				{children}
				<Toaster />
			</body>
		</html>
	);
}
