import type { ColumnConfig } from "@/features/shared/ui/table";

export const positionLabels: Record<string, string> = {
	accountant: "حسابدار",
	employee: "کارمند",
	manager: "مدیر",
	other: "سایر",
	owner: "مالک",
	secretary: "منشی",
};

export const getContactsColumnConfig = (): ColumnConfig[] => [
	{
		accessorKey: "firstName",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "نام",
		size: 150,
		sortableFieldName: "firstName",
	},
	{
		accessorKey: "lastName",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "نام خانوادگی",
		size: 150,
		sortableFieldName: "lastName",
	},
	{
		accessorKey: "phone",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "تلفن",
		size: 140,
		sortableFieldName: "phone",
	},
	{
		accessorKey: "position",
		enableFiltering: true,
		enableSorting: false,
		filterType: "select-single",
		header: "موقعیت در سازمان",
		selectOptions: [
			{ label: "مالک", value: "owner" },
			{ label: "مدیر", value: "manager" },
			{ label: "حسابدار", value: "accountant" },
			{ label: "منشی", value: "secretary" },
			{ label: "کارمند", value: "employee" },
			{ label: "سایر", value: "other" },
		],
		size: 180,
		sortableFieldName: "position",
	},
	{
		accessorKey: "email",
		enableFiltering: true,
		enableSorting: true,
		filterType: "text",
		header: "ایمیل",
		size: 200,
		sortableFieldName: "email",
	},
	{
		accessorKey: "createdAt",
		enableFiltering: false,
		enableSorting: true,
		filterType: "text",
		header: "تاریخ ایجاد",
		size: 160,
		sortableFieldName: "createdAt",
	},
	{
		accessorKey: "assignedToUserId",
		enableFiltering: true,
		enableSorting: false,
		filterType: "select-single",
		header: "ارجاع به",
		selectOptions: [
			{ label: "یوزر 1", value: "1" },
			{ label: "یوزر 2", value: "9" },
		],
		size: 140,
		sortableFieldName: "assignedToUserId",
	},
];
