import type { ColumnConfig } from "@/features/shared/ui/table";
import type { UserOption } from "@/store/useUserStore.";

export const positionLabels: Record<string, string> = {
  accountant: "حسابدار",
  employee: "کارمند",
  manager: "مدیر",
  other: "سایر",
  owner: "مالک",
  secretary: "منشی",
};

export const getContactsColumnConfig = (users: UserOption[] = []): ColumnConfig[] => [
  {
    accessorKey: "firstName",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "نام",
    size: 150,
    sortableFieldName: "firstName",
  },
  {
    accessorKey: "lastName",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "نام خانوادگی",
    size: 150,
    sortableFieldName: "lastName",
  },
  {
    accessorKey: "phone",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "تلفن",
    size: 140,
    sortableFieldName: "phone",
  },
  {
    accessorKey: "position",
    badge: {
      owner: {
        bgColor: "#8b5cf6",
        label: "مالک",
        textColor: "#ffffff",
        value: "owner",
      },
      manager: {
        bgColor: "#3b82f6",
        label: "مدیر",
        textColor: "#ffffff",
        value: "manager",
      },
      accountant: {
        bgColor: "#10b981",
        label: "حسابدار",
        textColor: "#ffffff",
        value: "accountant",
      },
      secretary: {
        bgColor: "#f59e0b",
        label: "منشی",
        textColor: "#ffffff",
        value: "secretary",
      },
      employee: {
        bgColor: "#06b6d4",
        label: "کارمند",
        textColor: "#ffffff",
        value: "employee",
      },
      other: {
        bgColor: "#64748b",
        label: "سایر",
        textColor: "#ffffff",
        value: "other",
      },
    },
    enableFiltering: true,
    enableSorting: false,
    filterType: "select-single",
    header: "موقعیت در سازمان",
    selectOptions: [
      { label: "مالک", value: "owner" },
      { label: "مدیر", value: "manager" },
      { label: "حسابدار", value: "accountant" },
      { label: "منشی", value: "secretary" },
      { label: "کارمند", value: "employee" },
      { label: "سایر", value: "other" },
    ],
    size: 180,
    sortableFieldName: "position",
  },
  {
    accessorKey: "email",
    enableFiltering: true,
    enableSorting: true,
    filterType: "text",
    header: "ایمیل",
    size: 200,
    sortableFieldName: "email",
  },
  {
    accessorKey: "createdAt",
    enableFiltering: false,
    enableSorting: true,
    filterType: "text",
    header: "تاریخ ایجاد",
    size: 160,
    sortableFieldName: "createdAt",
  },
  {
    accessorKey: "assignedToUserId",
    enableFiltering: true,
    enableSorting: false,
    filterType: "select-single",
    header: "ارجاع به",
    selectOptions: users.map((user) => ({
      label: user.label,
      value: String(user.value),
    })),
    size: 140,
    sortableFieldName: "assignedToUserId",
  },
];
